### ISSUE TITLE
好奇一个细节

### ISSUE THREAD

**Issue by mundane799699** [xiaosimao/transfrom_zhihu_answer_to_md#1]
代码完全ok. 但是楼主, zhihu.py第46行, first_url_format那个, 我观察过知乎的页面, 没有这么短的, 是类似'https://www.zhihu.com/api/v4/questions/24400664/answers?sort_by=default&include=data%5B%2A%5D.is_normal%2Cadmin_closed_comment%2Creward_info%2Cis_collapsed%2Cannotation_action%2Cannotation_detail%2Ccollapse_reason%2Cis_sticky%2Ccollapsed_by%2Csuggest_edit%2Ccomment_count%2Ccan_comment%2Ccontent%2Ceditable_content%2Cvoteup_count%2Creshipment_settings%2Ccomment_permission%2Ccreated_time%2Cupdated_time%2Creview_info%2Crelevant_info%2Cquestion%2Cexcerpt%2Crelationship.is_authorized%2Cis_author%2Cvoting%2Cis_thanked%2Cis_nothelp%2Cupvoted_followees%3Bdata%5B%2A%5D.mark_infos%5B%2A%5D.url%3Bdata%5B%2A%5D.author.follower_count%2Cbadge%5B%3F%28type%3Dbest_answerer%29%5D.topics&limit=20&offset=23' 这种超长的, 但是你这个这么短的居然也能得到数据, 是怎么发现的?

**Comment by xiaosimao** [comment]
我忘了、、、

**Comment by mundane799699** [comment]
好吧, 时间这么久了, 忘了也正常的
